/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ProductPrice } from "./components/fn-product-card/fn-product-card";
export namespace Components {
    interface FnProductCard {
        "code": string;
        "image": string;
        "name": string;
        "price": ProductPrice;
        "tags": [];
    }
    interface FnTag {
        "isHighlight": boolean;
        "nameTag": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLFnProductCardElement extends Components.FnProductCard, HTMLStencilElement {
    }
    var HTMLFnProductCardElement: {
        prototype: HTMLFnProductCardElement;
        new (): HTMLFnProductCardElement;
    };
    interface HTMLFnTagElement extends Components.FnTag, HTMLStencilElement {
    }
    var HTMLFnTagElement: {
        prototype: HTMLFnTagElement;
        new (): HTMLFnTagElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "fn-product-card": HTMLFnProductCardElement;
        "fn-tag": HTMLFnTagElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface FnProductCard {
        "code"?: string;
        "image"?: string;
        "name"?: string;
        "price"?: ProductPrice;
        "tags"?: [];
    }
    interface FnTag {
        "isHighlight"?: boolean;
        "nameTag"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "fn-product-card": FnProductCard;
        "fn-tag": FnTag;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fn-product-card": LocalJSX.FnProductCard & JSXBase.HTMLAttributes<HTMLFnProductCardElement>;
            "fn-tag": LocalJSX.FnTag & JSXBase.HTMLAttributes<HTMLFnTagElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
