/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ProductImage, ProductPrice, ProductTag } from "./components/fn-product-card/fn-product-card";
export namespace Components {
    interface FnButton {
        /**
          * button name
         */
        "name": string;
    }
    interface FnProductCard {
        /**
          * Product code
         */
        "code": string;
        /**
          * Product image URL
         */
        "image": ProductImage;
        /**
          * Product name
         */
        "name": string;
        /**
          * Product price object
         */
        "price": ProductPrice;
        /**
          * Product tags
         */
        "tags": ProductTag[];
    }
    interface FnTag {
        "isHighlight": boolean;
        "nameTag": string;
    }
}
declare global {
    interface HTMLFnButtonElement extends Components.FnButton, HTMLStencilElement {
    }
    var HTMLFnButtonElement: {
        prototype: HTMLFnButtonElement;
        new (): HTMLFnButtonElement;
    };
    interface HTMLFnProductCardElement extends Components.FnProductCard, HTMLStencilElement {
    }
    var HTMLFnProductCardElement: {
        prototype: HTMLFnProductCardElement;
        new (): HTMLFnProductCardElement;
    };
    interface HTMLFnTagElement extends Components.FnTag, HTMLStencilElement {
    }
    var HTMLFnTagElement: {
        prototype: HTMLFnTagElement;
        new (): HTMLFnTagElement;
    };
    interface HTMLElementTagNameMap {
        "fn-button": HTMLFnButtonElement;
        "fn-product-card": HTMLFnProductCardElement;
        "fn-tag": HTMLFnTagElement;
    }
}
declare namespace LocalJSX {
    interface FnButton {
        /**
          * button name
         */
        "name"?: string;
    }
    interface FnProductCard {
        /**
          * Product code
         */
        "code"?: string;
        /**
          * Product image URL
         */
        "image"?: ProductImage;
        /**
          * Product name
         */
        "name"?: string;
        "onAddToCart"?: (event: CustomEvent<any>) => void;
        /**
          * Product price object
         */
        "price"?: ProductPrice;
        /**
          * Product tags
         */
        "tags"?: ProductTag[];
    }
    interface FnTag {
        "isHighlight"?: boolean;
        "nameTag"?: string;
    }
    interface IntrinsicElements {
        "fn-button": FnButton;
        "fn-product-card": FnProductCard;
        "fn-tag": FnTag;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fn-button": LocalJSX.FnButton & JSXBase.HTMLAttributes<HTMLFnButtonElement>;
            "fn-product-card": LocalJSX.FnProductCard & JSXBase.HTMLAttributes<HTMLFnProductCardElement>;
            "fn-tag": LocalJSX.FnTag & JSXBase.HTMLAttributes<HTMLFnTagElement>;
        }
    }
}
